DIRECTORIES: 
  gat_dir: "intermediateFiles/overlap_enrich"
  figures: "figures"
  gatResults: "os.path.join(config['DIRECTORIES']['gat_dir'], 'gatResults')"
  gatLogs: "os.path.join(config['DIRECTORIES']['gat_dir'], 'gatLogs')"
  gatCountsIntermediate: "os.path.join(config['DIRECTORIES']['gat_dir'], 'gatCountsIntermediate')"

DATA: 
  output: "{cell1}.{annotation1}.{cell2}.{annotation2}.gatResults.dat"
  count_output: "{cell1}.{annotation1}.{cell2}.{annotation2}.%s.countsOutput"
  log: "{cell1}.{annotation1}.{cell2}.{annotation2}.gatLog.dat"
  fig_output: "enrichment_GAT.pdf"
   
PARAMETERS:
  COMPILE_RESULTS: "expand(rules.runGAT.output.full, cell1 = ['GM12878','H1','HepG2','K562'], cell2 = ['GM12878','H1','HepG2','K562'], annotation1 = ['hotRegions','broadDomains','stretchEnhancer','superEnhancers','typicalEnhancers'], annotation2 = ['hotRegions','broadDomains','stretchEnhancer','superEnhancers','typicalEnhancers'])"
  num_samples: 10000
  filenameString: "*.gatResults.dat"
  colnames: "cell1 annotation1 cell2 annotation2"
        
SCRIPTS: 
  compileResults: "scripts/analyze_GATResults.py"
  plot: "scripts/plot_gat.R"                  
