DIRECTORIES: 
  gat_dir: "intermediateFiles/overlap_enrich"
  figures: "figures"
  gatResults: "os.path.join(config['DIRECTORIES']['gat_dir'], 'gatResults')"
  gatLogs: "os.path.join(config['DIRECTORIES']['gat_dir'], 'gatLogs')"
  gatCountsIntermediate: "os.path.join(config['DIRECTORIES']['gat_dir'], 'gatCountsIntermediate')"

DATA: 
  annotation: "/lab/work/arushiv/regulatoryAnnotations_comparisons/data/annotations/{cell1}.{annotation1}.annotations.bed"
  segment: "/lab/work/arushiv/regulatoryAnnotations_comparisons/data/annotations/{cell2}.{annotation2}.annotations.bed"
  workspace: "/lab/work/arushiv/chromatin/integrativeAnalysis_Chromhmm/annotations/hg19_chromsizes.bed"
  output: "{cell1}.{annotation1}.{cell2}.{annotation2}.gatResults.dat"
  count_output: "{cell1}.{annotation1}.{cell2}.{annotation2}.%s.countsOutput"
  log: "{cell1}.{annotation1}.{cell2}.{annotation2}.gatLog.dat"
  fig_output: "enrichment_GAT.pdf"
   
PARAMETERS:
  COMPILE_RESULTS: "expand(rules.runGAT.output.full, cell1 = ['GM12878','H1','HepG2','K562'], cell2 = ['GM12878','H1','HepG2','K562'], annotation1 = ['hotRegions','broadDomains','stretchEnhancer','superEnhancers','typicalEnhancers'], annotation2 = ['hotRegions','broadDomains','stretchEnhancer','superEnhancers','typicalEnhancers'])"
  num_samples: 10000
  filenameString: "*.gatResults.dat"
  colnames: "cell1 annotation1 cell2 annotation2"
        
SCRIPTS: 
  compileResults: "/home/arushiv/toolScripts/analyze_GATResults.py"
  plot: "scripts/plot_gat.R"                  
