# general
fdr : 0.1
maf : 0.0
# prune
population_type: "Superpopulation code"  # Choose which column in vcf_sampleInfo file to subset samples on. Another option could be "Population code" to subest by population
population_code: "EUR"
output_directory: "intermediateFiles/prune_and_proxies"  # Where output will be saved
prune_r2 : 0.8

