# prune
population_type: "Superpopulation code"  # Choose which column in vcf_sampleInfo file to subset samples on. Another option could be "Population code" to subest by population
population_code: "EUR"
output_directory: "intermediateFiles/prune"  # Where output will be saved
prune_r2 : 0.2
1000g_maf : 0.05 # Min MAF in popluation considered to avoid ultra low freq alleles that result in duplicate rsIDs due to which plink fails


DIRECTORIES :
  gregor_dir : "intermediateFiles/gregorRun"
  output_dir : "output_{trait}.ld{gregor_r2}"
  figures : "figures"

DATA :
  input_snps : "intermediateFiles/pruned0.2.{trait}.txt"
  output : "enrichment_stats.txt"
  output_fig : "fig.gwas_enrichment.pdf"
  
PARAMETERS : 
  gregor_version_path : "/lab/sw/modules/GREGOR/1.2.1/script/GREGOR.pl"
  config_name : "enrich.{trait}.ld{gregor_r2}.conf"
  POPULATION : "EUR"
  gregor_r2 : 0.8
  cores: 10
  nameFieldSeparator: '.'
  jobFieldSeparator : '.'
  header : "trait ld ldr2 cell annotation feature overlap expected_overlap pval"
  
SCRIPTS : 
  makeConfFile : "/home/arushiv/toolScripts/gregor_makeConf.py"
  assembleDF : "/home/arushiv/toolScripts/makeDataFrame_gregor_new.py"
  plot : "scripts/plot.R"

