SCRIPTS :
  # ChromHMM from conda
  chromhmm: "ChromHMM.sh"
  calculate_avgPosterior: "scripts/calculate_avgPosteriors.py"
  calculate_information: "scripts/calculateInformation.py"

PARAMETERS :
  cell :
    - "GM12878"
    - "HepG2"
    - "K562"
    - "H1"
    
  marks:
    - 'WCE'
    - 'H3K4me3'
    - 'H3K4me1'
    - 'H3K27ac'
    - 'H3K27me3'
    
  control : "WCE"
  assembly : "hg19_concise"

  # Number of states to run ChromHMM with 
  numStates : 13
